on:
  release:
    types:
      - created

name: release-artifact

jobs:
  github:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - run: echo "${GITHUB_REF#refs/tags/}"
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        timeout-minutes: 20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

  homebrew:
    name: Bump Homebrew formula
    needs:
      - github
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-path: unifi-doorbell-notifier.rb
          homebrew-tap: sawadashota/homebrew-tap
          base-branch: main
          download-url: https://github.com/sawadashota/unifi-doorbell-notifier/releases/download/${{ steps.extract-version.outputs.tag-name }}/unifi-doorbell-notifier_${{ steps.extract-version.outputs.tag-name }}_x86_64-apple-darwin.zip
        env:
          COMMITTER_TOKEN: ${{ secrets._GITHUB_TOKEN }}
